### ISSUE TITLE
Binaries in nuget package compiled in debug mode

### ISSUE THREAD

**Issue by caveman-dick** [altmann/FluentResults#195] opened 2023-10-05 16:37 UTC
Hi

I've just run debugdiag to check the perf of our site and I've just noticed that this isn't compiled in release mode:

![image](https://github.com/altmann/FluentResults/assets/516600/e9b79e7a-cdd3-419c-a8d6-b4772f906570)

**Comment by altmann** [comment] 2024-06-19 20:36
Thanks for your feedback. 

CLOSED - this issue is a duplicate of #194

**Closed by altmann** 2024-06-19 20:36 UTC
